# Generated by Django 4.2.6 on 2023-11-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Package_image',
            new_name='package_image',
        ),
    ]
