# Generated by Django 4.2.6 on 2023-11-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_booking_client_course_package_photo_booking_client_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
